--FIRST PART: SELECT RELEVANT POLYGONS AND POINTS; MAKE BUFFERS ON POINTS, WRITE GEOMS

DROP TABLE IF EXISTS :vOUT;
CREATE TABLE :vOUT AS

WITH latest_no_chn_no_ind AS (SELECT * FROM :vLAST WHERE iso3 NOT ILIKE '%CHN%' AND iso3 NOT ILIKE '%IND%')

SELECT * FROM latest_no_chn_no_ind
UNION
SELECT * FROM :vCHN
UNION
SELECT * FROM :vIND
ORDER BY wdpaid;

CREATE INDEX wdpa_for_carbon_vidx ON :vOUT USING gist(geom);

